spring:
  datasource:
    url: jdbc:h2:file:./db/microgram;AUTO_SERVER=TRUE;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    charset: UTF-8
    expose-session-attributes: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  sql:
    init:
      mode: never

server:
  port: 8082

app:
  upload:
    avatars: uploads/avatars
    posts: uploads/posts

  level:
    root: INFO
    com.microgram: DEBUG
    org.springframework.security: DEBUG